In [10]:
import numpy as np


u = np.array([1.0, 2.0, 3.0])
v = np.array([4.0, 5.0, 6.0])
w = np.array([7.0, 8.0, 9.0])

print("u = ", u)
print("v = ", v)
print("w = ", w)

M = np.column_stack((u, v, w))
print("Matrix M: ")
print(M)

print("Rank:")
print(M)

rank_M = np.linalg.matrix_rank(M)


print("Rank:",rank_M)
print("Number of vectors:", M.shape[1])
print("Linearly independent?", rank_M == M.shape[1])


A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Matrix A:")
print(A)

rank_A = np.linalg.matrix_rank(A)

print("Rank:", rank_A)
print("Linearly independent columns?", rank_A == A.shape[1])


x = np.array([3,4])


e_x = np.array([1,0])
e_y = np.array([0,1])

# Projection formula

proj_x = (np.dot(x, e_x) / np.dot(e_x, e_x)) * e_x
proj_y = (np.dot(x, e_y) / np.dot(e_y, e_y)) * e_y


print("Projection of x-axis:", proj_x)
print("Projection of y-axis:",proj_y)
print("Sum of projections:", proj_x + proj_y)

print( 
  "The projection is [3,0] and [0,4]."
  "They add to x, each residual is perpendicular to its axis"
)

b1 = np.array([1, 0])
b2 = np.array([1, -1])

B = np.column_stack((b1, b2))

coordinates = np.linalg.solve(B, x)

reconstructed_x = B @ coordinates

print("Basis matrix B:")
print(B)
print("Rank of B:", np.linalg.matrix_rank(B))
print("Coordinates of x in B:", coordinates)

print("Reconstructed x:", reconstructed_x)
print("Matches original x?", np.allclose(reconstructed_x, x))

print(
    "Interpretation: x = 3.5*b1 - 0.5*b2. "
    "Its coordinates in this basis are [3.5, -0.5]. "
    "B has rank 2, so its two columns form a basis for R^2."
)

assert np.allclose(u, [1.0, 2.0, 3.0])
assert np.allclose(v, [4.0, 5.0, 6.0])
assert np.allclose(w, [7.0, 8.0, 9.0])

assert np.allclose(M, np.column_stack((u, v, w)))
assert np.allclose(A, [[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Verify Problem 5(a).
assert np.linalg.matrix_rank(M) == 2
assert np.linalg.matrix_rank(A) == 2
assert np.allclose(-u + 2*v, w)
assert np.allclose(A @ np.array([1.0, -2.0, 1.0]), np.zeros(3))

# Verify Problems 5(b) and 5(c).
assert np.allclose(proj_x, [3.0, 0.0])
assert np.allclose(proj_y, [0.0, 4.0])
assert np.allclose(coordinates, [3.5, -0.5])
assert np.allclose(reconstructed_x, x)

print("All prerequisite 1 computational checks passed.")



u =  [1. 2. 3.]
v =  [4. 5. 6.]
w =  [7. 8. 9.]
Matrix M: 
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
Rank:
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
Rank: 2
Number of vectors: 3
Linearly independent? False
Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank: 2
Linearly independent columns? False
Projection of x-axis: [3. 0.]
Projection of y-axis: [0. 4.]
Sum of projections: [3. 4.]
The projection is [3,0] and [0,4].They add to x, each residual is perpendicular to its axis
Basis matrix B:
[[ 1  1]
 [ 0 -1]]
Rank of B: 2
Coordinates of x in B: [ 7. -4.]
Reconstructed x: [3. 4.]
Matches original x? True
Interpretation: x = 3.5*b1 - 0.5*b2. Its coordinates in this basis are [3.5, -0.5]. B has rank 2, so its two columns form a basis for R^2.


AssertionError: 