In [11]:
import numpy as np


u = np.array([1.0, 2.0, 3.0])
v = np.array([4.0, 5.0, 6.0])
w = np.array([7.0, 8.0, 9.0])

print("u =", u)
print("v =", v)
print("w =", w)

M = np.column_stack((u, v, w))
rank_M = np.linalg.matrix_rank(M)

print("\nMatrix M:")
print(M)
print("Rank:", rank_M)
print("Number of vectors:", M.shape[1])
print("Linearly independent?", rank_M == M.shape[1])

print(
    "Interpretation: There are three vectors but only two "
    "independent directions, so the vectors are linearly dependent."
)



A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])

rank_A = np.linalg.matrix_rank(A)

print("\nMatrix A:")
print(A)
print("Rank:", rank_A)
print("Linearly independent columns?", rank_A == A.shape[1])

print(
    "Interpretation: A has rank 2 and three columns, "
    "so its columns are linearly dependent."
)


x = np.array([3.0, 4.0])

e_x = np.array([1.0, 0.0])
e_y = np.array([0.0, 1.0])

proj_x = (np.dot(x, e_x) / np.dot(e_x, e_x)) * e_x
proj_y = (np.dot(x, e_y) / np.dot(e_y, e_y)) * e_y

print("\nProjection onto x-axis:", proj_x)
print("Projection onto y-axis:", proj_y)
print("Sum of projections:", proj_x + proj_y)


print("Residual dot x-axis:", np.dot(x - proj_x, e_x))
print("Residual dot y-axis:", np.dot(x - proj_y, e_y))

print(
    "Interpretation: The projections are [3, 0] and [0, 4]. "
    "They add to x, and each residual is perpendicular to its axis."
)

b1 = np.array([1.0, 1.0])
b2 = np.array([1.0, -1.0])

B = np.column_stack((b1, b2))

coordinates = np.linalg.solve(B, x)
reconstructed_x = B @ coordinates

print("\nBasis matrix B:")
print(B)
print("Rank of B:", np.linalg.matrix_rank(B))
print("Coordinates of x in B:", coordinates)
print("Reconstructed x:", reconstructed_x)
print("Matches original x?", np.allclose(reconstructed_x, x))

print(
    "Interpretation: x = 3.5*b1 - 0.5*b2. "
    "Its coordinates in this basis are [3.5, -0.5]. "
    "B has rank 2, so its two columns form a basis for R^2."
)


u = [1. 2. 3.]
v = [4. 5. 6.]
w = [7. 8. 9.]

Matrix M:
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
Rank: 2
Number of vectors: 3
Linearly independent? False
Interpretation: There are three vectors but only two independent directions, so the vectors are linearly dependent.

Matrix A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Rank: 2
Linearly independent columns? False
Interpretation: A has rank 2 and three columns, so its columns are linearly dependent.

Projection onto x-axis: [3. 0.]
Projection onto y-axis: [0. 4.]
Sum of projections: [3. 4.]
Residual dot x-axis: 0.0
Residual dot y-axis: 0.0
Interpretation: The projections are [3, 0] and [0, 4]. They add to x, and each residual is perpendicular to its axis.

Basis matrix B:
[[ 1.  1.]
 [ 1. -1.]]
Rank of B: 2
Coordinates of x in B: [ 3.5 -0.5]
Reconstructed x: [3. 4.]
Matches original x? True
Interpretation: x = 3.5*b1 - 0.5*b2. Its coordinates in this basis are [3.5, -0.5]. B has rank 2, so its two columns form a basis for R^2.
